### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by chungyau97** [shravankumar147/Facial-Landmark-Detection#2]
I modify your code to intake vid and process it.
How come the result is like this? 
# Face landmarks Detection
# usage:
# python facelandmarkdetect.py --shape-predictor shape_predictor_68_face_landmarks.dat --image images/face1.jpg

# import the necessary packages
from imutils import face_utils
import numpy as np
import argparse
import os
import imutils
import dlib
import cv2
import matplotlib.pyplot as plt

# construct the argument parser and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-p", "--shape-predictor", required=False,
	help="path to facial landmark predictor")
ap.add_argument("-i", "--image", required=False,
	help="path to input image")
args = vars(ap.parse_args())

cwd = os.getcwd()
for filename in os.listdir('models'):
	if filename == 'shape_predictor_68_face_landmarks.dat':
		filepath = cwd + '\\models\\' + filename
	else:
		print("Oops...! File is not available.")
		# cmd = "wget -c --progress=bar http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2"
		# os.system(cmd)
		exit(0)
# initialize dlib's face detector (HOG-based) and then create
# the facial landmark predictor
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(filepath)

# load the input image, resize it, and convert it to grayscale
cap = cv2.VideoCapture(0)

while cap.isOpened():
	ret, frame = cap.read()
	if ret is True:
		orig = frame
		image = imutils.resize(frame, width=500)
		gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
		# detect faces in the grayscale image
		rects = detector(gray, 1)

		# loop over the face detections
		for (i, rect) in enumerate(rects):
			# determine the facial landmarks for the face region, then
			# convert the facial landmark (x, y)-coordinates to a NumPy
			# array
			shape = predictor(gray, rect)
			shape = face_utils.shape_to_np(shape)

			# convert dlib's rectangle to a OpenCV-style bounding box
			# [i.e., (x, y, w, h)], then draw the face bounding box
			(x, y, w, h) = face_utils.rect_to_bb(rect)
			cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)

			# show the face number
			cv2.putText(image, "Face #{}".format(i + 1), (x - 10, y - 10),
				cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

			# loop over the (x, y)-coordinates for the facial landmarks
			# and draw them on the image
			for (x, y) in shape:
				cv2.circle(image, (x, y), 1, (0, 0, 255), -1)

		# show the output image with the face detections + facial landmarks
	cv2.imshow('Landmark',image)

	if cv2.waitKey(1) & 0xFF == ord('q'):
		cap.release()
		cv2.destroyAllWindows()
		break

![image](https://user-images.githubusercontent.com/33013947/55125401-86a38480-5144-11e9-8b6d-7dac8516d447.png)

**Comment by shravankumar147** [comment]
I appreciate your experiment, the current issue is probably due to : 

`
 convert dlib's rectangle to a OpenCV-style bounding box
 [i.e., (x, y, w, h)], then draw the face bounding box
(x, y, w, h) = face_utils.rect_to_bb(rect)
cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)
`

Make sure of bounding box co-ordinates.

**Comment by chungyau97** [comment]
image = imutils.resize(image, width=500)
By removing this, fix the problem

**Comment by chungyau97** [comment]
The actual culprit in my code is 
I put in the wrong parameter for image.
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
